<jsp:useBean id="id1" class="clicks.clicks.Display" scope="session" />
<jsp:setProperty name="id1" property="*" />
<%! int i=0; int j; int tqty=0; %>
<html>
	<head>
		<style type="text/css">
			*{
				padding:0px;
				margin:0px;
			}
			body{
				width:100%;
				display:-webkit-box;
				-webkit-box-pack:center;
			}
			#main{
				width:1355px;
				max-height:660px;
				border:1px solid red;
				display:-webkit-box;
				-webkit-box-orient:vertical;
				-webkit-box-pack:center;
				background-image:url(images/background.jpg);
			}
			#tab{
				margin-left:15%;
				margin-top:0.5%;
				border:1px solid black;
			}
			#b{
				width:30%;
				height:3%;
				margin-top:0.4%;
				margin-left:55%;
			}
			#bo td{
				border-bottom:1px solid black;
			}
			.bor td{
				border-left:1px solid black;
			}
			#top td{
				border-top:1px solid black;
			}
			#button{
				height:110%;
				width:30%;
				font-family:italic;
				font-weight:bold;
			}
			#button:hover{
				color:red;
			}
		</style>
		<script type="text/javascript">
			window.onload=fun1;
			function fun1()
			{	date=new Date();
				hour=date.getHours();
				min=date.getMinutes();
				sec=date.getSeconds();
				day=date.getDate();
				month=date.getMonth()+1;
				year=date.getFullYear();
				i1=date.getDay();
				ms=date.getMilliseconds();
				wday=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
				curdate=year+"-"+month+"-"+day;
				if(hour<10)
					curtime="0"+hour;
				else
					curtime=hour;
				if(min<10)
					curtime=curtime+":0"+min;
				else
					curtime=curtime+":"+min;
				document.getElementById("dt1").value=curdate;
				document.getElementById("dt2").value=curtime;
				document.getElementById("cid").value=day+""+month+""+date.getYear()+""+hour+""+min+""+sec+""+ms;
			}
			function getmon(){
				return ((month==1)?"Jan":((month==2)?"Feb":((month==3)?"Mar":((month==4)?"Apr":((month==5)?"May":((month==6)?"June":((month==7)?"July":((month==8)?"Aug":((month==9)?"Sept":((month==10)?"Oct":((month==11)?"Nov":"Dec")))))))))));
			}
		</script>
	</head>
	<body>
		<div id="main">
			<h2 style="text-align:center;font-style:italic;" width="100%">VERIFY YOUR ORDER!</h2>
			
			<% 	String s1[]=id1.getItem();
				String s2[]=id1.getQty();
				String s3[]=id1.getCost();
				String cost=id1.getTot();
				for(j=0;j<s2.length;j++)
				{	if(!s2[j].equals(""))
						tqty+=Integer.parseInt(s2[j]);
				}
			%>
			<form method="POST" action="payment.jsp">
				<table id="tab" height="88%" width="70%">
					<tr id="bo" height="8%">
						<td width="30%" style="text-align:center">Customer ID(generated by system) : </td>
						<td width="25%"><input type="text" id="cid" name="custid" style="text-align:center;border:none;background:none;" readonly /></td>
						<td width="15%" style="text-align:center">Date & Time of Order :</td>
						<td><input type="text" name="date" id="dt1" size="8" style="text-align:center;border:none;background:none;" readonly />
							<input type="text" name="time" id="dt2" size="5" style="text-align:center;border:none;background:none;" readonly />
						</td>
					</tr>
					<tr id="bo" class="bor" height="5%" style="text-align:center">
						<td colspan="2">NAME OF ITEM(s)</td>
						<td>QUANTITY</td>
						<td>COST</td>
					</tr>
					<%	for(i=0;i<j;i++)
						{	
					%>
					<tr class="bor" style="text-align:center">
						<td colspan="2"><input type="text" name="item" size="80" value="<% out.println(s1[i]); %>" style="text-align:center;border:none;background:none;" readonly /></td> 
						<td><input type="text" name="qty" value="<% out.println(s2[i]); %>" style="text-align:center;border:none;background:none;" readonly /></td>
						<td><input type="text" name="cost" value="<% out.println(s3[i]); %>" style="text-align:center;border:none;background:none;" readonly /></td>
					</tr>
			
					<% } %>
					
					<tr id="top" class="bor" style="text-align:center;font-weight:bold;" height="5%">
						<td colspan="2">Total (including 5% tax)</td>
						<td><input type="text" name="tqty" value="<%=tqty%>" style="text-align:center;border:none;background:none;font-weight:bold;" readonly /></td>
						<td><input type="text" name="tot" value="<%=cost%>" style="text-align:center;border:none;background:none;font-weight:bold;" readonly /></td>
					</tr>
				
				</table>
				<div id="b">
					<a href="index.jsp"><input type="button" value="Cancel Order" id="button" /></a>
					<input type="submit" value="Make Payment" style="margin-left:20%;" id="button" />
				</div>
			</form>
		</div>
	</body>
</html>
<%tqty*=0;%>